#!/usr/bin/env node
// build-sitemap.js — regenerates sitemap.xml with the root URL plus one
// per-item permalink (/?item=<id>) for every story in the live feed and the
// archive. Item ids are stable across cron runs (news-refresh.js reuses the
// archived identity per canonical URL), so these URLs don't churn.
//
// Query-param URLs are distinct, indexable URLs to Google; the app renders a
// per-item detail overlay with its own title/canonical/JSON-LD at that URL
// (Googlebot renders the React app fully — confirmed in GSC).
//
// Called at the end of scripts/news-refresh.js on each cron run; can also be
// run standalone: node scripts/build-sitemap.js

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE_URL = (process.env.SITE_URL || 'https://incadencept.com').replace(/\/$/, '');

function buildSitemap() {
  const xmlEsc = (s) => (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');

  // Collect items: live feed first, then archive months; dedupe by id AND by
  // sourceUrl (an item can sit in both news.json and an archive month file —
  // and if id churn ever recurs, the same story could carry two ids; the
  // sourceUrl guard keeps the sitemap from emitting a dead second URL).
  const seen = new Set();
  const seenUrl = new Set();
  const items = [];
  const take = (list) => {
    for (const i of list || []) {
      if (!i || !i.id || seen.has(i.id)) continue;
      if (i.sourceUrl && seenUrl.has(i.sourceUrl)) continue;
      seen.add(i.id);
      if (i.sourceUrl) seenUrl.add(i.sourceUrl);
      items.push(i);
    }
  };
  try { take(JSON.parse(fs.readFileSync(path.join(ROOT, 'news.json'), 'utf8')).items); } catch {}
  try {
    const dir = path.join(ROOT, 'archive');
    for (const f of fs.readdirSync(dir).sort().reverse()) {
      if (!/^\d{4}-\d{2}\.json$/.test(f)) continue;
      try { take(JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')).items); } catch {}
    }
  } catch {}

  const day = (iso) => (iso || '').slice(0, 10);
  const urls = [
    `  <url>\n    <loc>${SITE_URL}/</loc>\n    <changefreq>daily</changefreq>\n    <priority>1.0</priority>\n  </url>`,
    ...items.map((i) => {
      const lastmod = day(i.firstSeen) || day(i.publishedAt);
      return `  <url>\n    <loc>${SITE_URL}/?item=${xmlEsc(encodeURIComponent(i.id))}</loc>` +
        (lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : '') +
        `\n  </url>`;
    }),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.js (run by the news-refresh cron).
     Root + one /?item=<id> permalink per story (live feed + archive). -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;
  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);
  return { urls: urls.length };
}

module.exports = { buildSitemap };

if (require.main === module) {
  const { urls } = buildSitemap();
  console.log(`sitemap.xml written — ${urls} URLs`);
}
