/**
 * Cadence 步频 — 小红书日报卡片生成器
 *
 * Reads the archive (superset of the feed — see archive/*.json) and renders
 * yesterday's top-scoring stories as XHS-ready 3:4 image cards plus a
 * paste-ready caption. No LLM call: titleZh / summaryZh / curatedReason were
 * already generated by the curation cron, so this step is deterministic and
 * free to run anywhere.
 *
 * Output (xhs/YYYY-MM-DD/):
 *   cover.png            3:4 封面 (1242×1656)，头条标题做钩子
 *   01.png … 0N.png      每篇一张内页卡
 *   0(N+1).png           尾页：标签档位说明 + 关注引导
 *   caption.txt          小红书标题 + 正文 + 话题标签
 *
 * Selection: stories published on the Beijing-time "yesterday" (or the date
 * passed as argv[2]), pulled from archive monthly files so stories already
 * rotated out of news.json still make the digest. Top 8 by curatedScore;
 * if yesterday has fewer than 5, the day before is folded in.
 *
 * Fonts: Noto Sans SC 400/500/700 + Noto Serif SC 700, resolved from the
 * @expo-google-fonts devDependencies (TTF, OFL-licensed).
 *
 * Usage:
 *   node scripts/xhs-digest.js              → yesterday (Beijing)
 *   node scripts/xhs-digest.js 2026-06-10   → explicit date
 */

const fs = require('fs');
const path = require('path');

// CADENCE_ROOT override lets the script run from outside the repo (e.g. a
// sandbox with its own node_modules) while reading/writing the real data.
const ROOT = process.env.CADENCE_ROOT || path.join(__dirname, '..');
const OUT_ROOT = process.env.XHS_OUT || path.join(ROOT, 'xhs');
const MAX_ITEMS = 8;
const MIN_ITEMS = 5;
// One-off "精选/合集" framing (run with DIGEST_MODE=curated) for posting a
// backlog of earlier high-scoring items. Story selection is unchanged; only the
// dateless wording differs (cover headline + footer, caption title + intro), so
// a post made today isn't mislabeled "昨日". Default (unset) keeps daily wording.
const CURATED = process.env.DIGEST_MODE === 'curated';
const HEADLINE = CURATED ? '近期高分文献' : '昨日高分文献';

// 1242×1656 = 小红书 3:4 竖版标准
const W = 1242, H = 1656;

// ── Brand tokens (mirrors design-system/tokens/colors.css) ──────────────────
const C = {
  paper: '#F7F9FB', white: '#FFFFFF',
  ink900: '#16202B', ink600: '#4D5965', ink500: '#64717F', ink200: '#DFE5EA', ink50: '#F4F7FA',
  blue700: '#2C5A96', blue100: '#E2EDF8', blue50: '#F2F7FC',
};

const CAT = {
  orthopedic:      { zh: '骨科与肌骨', soft: '#E8EAF1', ink: '#2B3850' },
  neurological:    { zh: '神经康复',   soft: '#E9E6F1', ink: '#332D5C' },
  sports:          { zh: '运动康复',   soft: '#F5E6DD', ink: '#75361F' },
  pediatric:       { zh: '儿童康复',   soft: '#F2EAD3', ink: '#694E12' },
  geriatric:       { zh: '老年康复',   soft: '#DFEAE6', ink: '#22463D' },
  cardiopulmonary: { zh: '心肺康复',   soft: '#F4E2E3', ink: '#6A2C32' },
  'manual-modality': { zh: '手法与理疗', soft: '#EBEEDB', ink: '#3E4621' },
  practice:        { zh: '行业与执业', soft: '#E8EAEC', ink: '#31363D' },
};
const catOf = (id) => CAT[id] || { zh: id || '其他', soft: C.ink50, ink: C.ink600 };

// 信号分 → 人话三档（分布实测 60–85，中位 75）；尾页有统一说明
const tierOf = (score) => (score >= 80 ? '强信号' : score >= 70 ? '值得读' : '参考');

// ── Data ─────────────────────────────────────────────────────────────────────
function beijingToday() {
  // en-CA locale formats as YYYY-MM-DD
  return new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Shanghai' });
}
function shiftDate(ymd, days) {
  const d = new Date(ymd + 'T12:00:00Z');
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

function loadPool() {
  // Archive is the strict superset of the feed; fall back to news.json if the
  // archive doesn't exist yet (fresh fork).
  const byKey = new Map();
  const add = (item) => {
    const k = item.sourceUrl || item.title;
    if (k && !byKey.has(k)) byKey.set(k, item);
  };
  const idxPath = path.join(ROOT, 'archive', 'index.json');
  if (fs.existsSync(idxPath)) {
    const manifest = JSON.parse(fs.readFileSync(idxPath, 'utf8'));
    for (const m of manifest.months || []) {
      const p = path.join(ROOT, 'archive', m.file);
      if (!fs.existsSync(p)) continue;
      for (const it of JSON.parse(fs.readFileSync(p, 'utf8')).items || []) add(it);
    }
  }
  for (const it of JSON.parse(fs.readFileSync(path.join(ROOT, 'news.json'), 'utf8')).items || []) add(it);
  return [...byKey.values()];
}

function pickStories(pool, dateStr) {
  const onDay = (d) => pool.filter((i) => (i.publishedAt || '').slice(0, 10) === d);
  let picked = onDay(dateStr);
  let spansTwoDays = false;
  if (picked.length < MIN_ITEMS) {
    picked = picked.concat(onDay(shiftDate(dateStr, -1)));
    spansTwoDays = true;
  }
  picked.sort((a, b) => (b.curatedScore || 0) - (a.curatedScore || 0));
  return { stories: picked.slice(0, MAX_ITEMS), spansTwoDays };
}

// ── Text helpers ─────────────────────────────────────────────────────────────
const trim = (s, n) => {
  s = (s || '').trim();
  return s.length > n ? s.slice(0, n - 1).replace(/[，。；、：,.;: ]+$/, '') + '…' : s;
};
const zhDate = (ymd) => {
  const [y, m, d] = ymd.split('-').map(Number);
  const wd = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'][new Date(ymd + 'T12:00:00Z').getUTCDay()];
  return { full: `${y}年${m}月${d}日`, short: `${m}.${d}`, weekday: wd };
};

// ── satori element helper ────────────────────────────────────────────────────
const h = (type, style, ...children) => ({
  type,
  props: { style, children: children.length === 1 ? children[0] : children },
});
const row = (style, ...kids) => h('div', { display: 'flex', flexDirection: 'row', alignItems: 'center', ...style }, ...kids);
const col = (style, ...kids) => h('div', { display: 'flex', flexDirection: 'column', ...style }, ...kids);
const txt = (style, s) => h('div', { display: 'flex', ...style }, String(s));

const SANS = 'Noto Sans SC', SERIF = 'Noto Serif SC';

// Shared page chrome: brand bar on top, hairline + footer on the bottom.
function pageShell(footerRight, ...body) {
  return col({ width: W, height: H, backgroundColor: C.paper, padding: '72px 84px 60px', justifyContent: 'space-between' },
    col({ flex: 1, width: '100%' },
      row({ justifyContent: 'space-between', marginBottom: 56 },
        row({ gap: 14 },
          h('div', { display: 'flex', width: 16, height: 16, borderRadius: 99, backgroundColor: C.blue700 }),
          txt({ fontFamily: SANS, fontWeight: 700, fontSize: 30, letterSpacing: 2, color: C.ink900 }, 'CADENCE 步频'),
        ),
        txt({ fontFamily: SANS, fontWeight: 500, fontSize: 26, color: C.ink500, letterSpacing: 4 }, '步频日报'),
      ),
      ...body,
    ),
    col({ width: '100%' },
      h('div', { display: 'flex', width: '100%', height: 2, backgroundColor: C.ink200, marginBottom: 26 }),
      row({ justifyContent: 'space-between' },
        txt({ fontFamily: SANS, fontSize: 24, color: C.ink500 }, 'AI 评分策展 · 每日更新'),
        txt({ fontFamily: SANS, fontWeight: 500, fontSize: 24, color: C.ink500 }, footerRight),
      ),
    ),
  );
}

// 封面：头条标题做钩子（品牌框架恒定），TOP n 降级为栏目标签，篇数放日期行
function coverCard(dateStr, stories) {
  const d = zhDate(dateStr);
  const lead = stories[0];
  const rest = stories.slice(1, 3);
  const cat = catOf(lead.category);
  return pageShell(CURATED ? `步频精选 · 共 ${stories.length} 篇` : `${d.full} · ${d.weekday} · 共 ${stories.length} 篇`,
    col({ flex: 1, justifyContent: 'center' },
      txt({ fontFamily: SANS, fontWeight: 700, fontSize: 30, color: C.blue700, letterSpacing: 8, marginBottom: 40 }, `${HEADLINE} TOP ${stories.length}`),
      txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 84, lineHeight: 1.38, color: C.ink900, marginBottom: 40, lineClamp: 4 },
        trim(lead.titleZh || lead.title, 44)),
      row({ gap: 16, marginBottom: 56 },
        h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: cat.soft },
          txt({ fontFamily: SANS, fontWeight: 500, fontSize: 27, color: cat.ink }, cat.zh)),
        h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: C.blue100 },
          txt({ fontFamily: SANS, fontWeight: 700, fontSize: 27, color: C.blue700 }, `今日最高 · ${tierOf(lead.curatedScore)}`)),
      ),
      h('div', { display: 'flex', width: 72, height: 3, backgroundColor: C.ink200, marginBottom: 44 }),
      col({ gap: 26 },
        ...rest.map((s, i) => row({ gap: 22, alignItems: 'flex-start' },
          txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 38, color: C.ink500, marginTop: -2 }, String(i + 2)),
          txt({ fontFamily: SANS, fontWeight: 500, fontSize: 31, lineHeight: 1.5, color: C.ink600, flex: 1, lineClamp: 2 }, trim(s.titleZh || s.title, 48)),
        )),
        stories.length > 3
          ? txt({ fontFamily: SANS, fontSize: 28, color: C.ink500, marginTop: 8 }, `…还有 ${stories.length - 3} 篇，往后翻 →`)
          : null,
      ),
    ),
  );
}

function storyCard(s, rank, total, dateStr) {
  const cat = catOf(s.category);
  const d = zhDate((s.publishedAt || dateStr).slice(0, 10));
  const journal = s.journal || s.source || '';
  return pageShell(`${rank}/${total}`,
    col({ flex: 1 },
      row({ gap: 18, marginBottom: 44 },
        txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 76, color: C.blue700, marginRight: 8 }, String(rank).padStart(2, '0')),
        h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: cat.soft },
          txt({ fontFamily: SANS, fontWeight: 500, fontSize: 27, color: cat.ink }, cat.zh)),
        s.tech ? h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: '#DFEDEE' },
          txt({ fontFamily: SANS, fontWeight: 500, fontSize: 27, color: '#1E5258' }, '康复科技')) : null,
        s.studyDesign ? h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: C.ink50, border: `1px solid ${C.ink200}` },
          txt({ fontFamily: SANS, fontWeight: 500, fontSize: 27, color: C.ink600 }, s.studyDesign)) : null,
        h('div', { display: 'flex', padding: '8px 22px', borderRadius: 10, backgroundColor: C.blue100 },
          txt({ fontFamily: SANS, fontWeight: 700, fontSize: 27, color: C.blue700 }, tierOf(s.curatedScore))),
      ),
      col({ flex: 1, justifyContent: 'center' },
        txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 56, lineHeight: 1.42, color: C.ink900, marginBottom: 44, lineClamp: 4 },
          trim(s.titleZh || s.title, 64)),
        txt({ fontFamily: SANS, fontSize: 32, lineHeight: 1.82, color: C.ink600, marginBottom: 52, lineClamp: 8 },
          trim(s.summaryZh || s.summary, 210)),
        row({ width: '100%', alignItems: 'stretch', gap: 0 },
          h('div', { display: 'flex', width: 6, borderRadius: 99, backgroundColor: C.blue700, marginRight: 26 }),
          col({ flex: 1, gap: 12, padding: '4px 0' },
            txt({ fontFamily: SANS, fontWeight: 700, fontSize: 26, letterSpacing: 4, color: C.blue700 }, '为什么重要'),
            txt({ fontFamily: SANS, fontSize: 30, lineHeight: 1.74, color: C.ink600, lineClamp: 6 }, trim(s.curatedReason, 150)),
          ),
        ),
      ),
      row({ gap: 16, marginTop: 30 },
        journal ? txt({ fontFamily: SANS, fontWeight: 500, fontSize: 26, color: C.ink600, lineClamp: 1, maxWidth: 760 }, journal) : null,
        txt({ fontFamily: SANS, fontSize: 26, color: C.ink500 }, `${d.full}`),
      ),
    ),
  );
}

// 尾页：收口 + 标签档位说明 + 关注/公众号引导
function endCard(dateStr, stories, meta) {
  const d = zhDate(dateStr);
  return pageShell(`${d.full} · ${d.weekday}`,
    col({ flex: 1, justifyContent: 'center' },
      txt({ fontFamily: SANS, fontWeight: 700, fontSize: 30, color: C.blue700, letterSpacing: 8, marginBottom: 44 }, '今天就到这里'),
      col({ marginBottom: 44 },
        txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 84, lineHeight: 1.4, color: C.ink900 }, '每天一份'),
        txt({ fontFamily: SERIF, fontWeight: 700, fontSize: 84, lineHeight: 1.4, color: C.ink900 }, '步频日报'),
      ),
      txt({ fontFamily: SANS, fontSize: 31, lineHeight: 1.74, color: C.ink600, marginBottom: 64 },
        `${meta.journalCount ? `监测 ${meta.journalCount} 本 PT/康复期刊，` : ''}AI 通读每天的新文献，只留最值得看的几篇`),
      row({ width: '100%', alignItems: 'stretch', marginBottom: 72 },
        h('div', { display: 'flex', width: 6, borderRadius: 99, backgroundColor: C.blue700, marginRight: 26 }),
        col({ flex: 1, gap: 12, padding: '4px 0' },
          txt({ fontFamily: SANS, fontWeight: 700, fontSize: 26, letterSpacing: 4, color: C.blue700 }, '图上的标签怎么读'),
          txt({ fontFamily: SANS, fontSize: 30, lineHeight: 1.74, color: C.ink600 },
            'AI 给每篇新文献打分后换算成三档：强信号（80 分以上）· 值得读（70–79）· 参考（70 以下）'),
        ),
      ),
      col({ padding: '36px 40px', borderRadius: 16, backgroundColor: C.blue50, border: `1px solid ${C.ink200}`, gap: 14 },
        txt({ fontFamily: SANS, fontWeight: 700, fontSize: 32, color: C.ink900 }, '关注 @Cadence步频，每天跟上新证据'),
        txt({ fontFamily: SANS, fontSize: 28, lineHeight: 1.6, color: C.ink600 }, '公众号同名「Cadence步频」，同步日更'),
      ),
    ),
  );
}

// ── Caption ──────────────────────────────────────────────────────────────────
function buildCaption(dateStr, stories, spansTwoDays) {
  const d = zhDate(dateStr);
  const lead = stories[0];
  const title = CURATED
    ? `步频精选｜近期康复高分文献 Top${stories.length}`
    : `${d.short} 步频日报｜昨日高分文献Top${stories.length}`;
  const lines = stories.map((s, i) => `${i + 1}️⃣ ${CURATED ? (s.titleZh || s.title) : trim(s.titleZh || s.title, 40)}`);
  const cats = [...new Set(stories.map((s) => catOf(s.category).zh))];
  const body = [
    CURATED
      ? `我们帮你刷完了近期的康复新文献，精选 ${stories.length} 篇最值得看的👇`
      : `我们帮你刷完了${spansTwoDays ? '这两天' : '昨天'}的康复新文献，挑出 ${stories.length} 篇最值得看的👇`,
    '',
    ...lines,
    '',
    `📌 最高分：${CURATED ? (lead.titleZh || lead.title) : trim(lead.titleZh || lead.title, 40)}（${tierOf(lead.curatedScore)}）`,
    `${CURATED ? lead.curatedReason : trim(lead.curatedReason, 80)}`,
    '',
    `涉及方向：${cats.join(' / ')}`,
    '每篇的摘要和「为什么重要」都在图里，翻完记得收藏～',
    '',
    '#康复 #物理治疗 #康复治疗师 #文献阅读 #康复医学 #循证医学 #科研日报 #PT',
  ].join('\n');
  return `${title}\n\n${body}\n`;
}

// ── Render ───────────────────────────────────────────────────────────────────
function fontFile(pkg, file) {
  return fs.readFileSync(require.resolve(`@expo-google-fonts/${pkg}/${file}`));
}

async function main() {
  const dateStr = process.argv[2] || shiftDate(beijingToday(), -1);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) { console.error(`Bad date: ${dateStr} (want YYYY-MM-DD)`); process.exit(1); }
  console.log(`\n📕 步频小红书日报 — ${dateStr}`);

  const pool = loadPool();
  const { stories, spansTwoDays } = pickStories(pool, dateStr);
  if (!stories.length) { console.log('  该日期没有文章，不出刊。'); return; }
  console.log(`  ${stories.length} 篇入选（池 ${pool.length} 条${spansTwoDays ? '，含前一天回填' : ''}）`);

  let journalCount = 0;
  try { journalCount = (JSON.parse(fs.readFileSync(path.join(ROOT, 'journals.json'), 'utf8')).journals || []).length; } catch (e) { /* optional */ }

  const satori = (await import('satori')).default;
  const { Resvg } = require('@resvg/resvg-js');
  const fonts = [
    { name: SANS, weight: 400, style: 'normal', data: fontFile('noto-sans-sc', '400Regular/NotoSansSC_400Regular.ttf') },
    { name: SANS, weight: 500, style: 'normal', data: fontFile('noto-sans-sc', '500Medium/NotoSansSC_500Medium.ttf') },
    { name: SANS, weight: 700, style: 'normal', data: fontFile('noto-sans-sc', '700Bold/NotoSansSC_700Bold.ttf') },
    { name: SERIF, weight: 700, style: 'normal', data: fontFile('noto-serif-sc', '700Bold/NotoSerifSC_700Bold.ttf') },
  ];

  const outDir = path.join(OUT_ROOT, dateStr);
  fs.mkdirSync(outDir, { recursive: true });

  const render = async (el, file) => {
    const svg = await satori(el, { width: W, height: H, fonts });
    const png = new Resvg(svg, { fitTo: { mode: 'width', value: W } }).render().asPng();
    fs.writeFileSync(path.join(outDir, file), png);
    console.log(`  ✓ ${file} (${(png.length / 1024).toFixed(0)} KB)`);
  };

  await render(coverCard(dateStr, stories), 'cover.png');
  for (let i = 0; i < stories.length; i++) {
    await render(storyCard(stories[i], i + 1, stories.length, dateStr), `${String(i + 1).padStart(2, '0')}.png`);
  }
  // 尾页接在最后一篇之后（8 篇时为 09.png），与编号图一起按文件名升序上传即可
  await render(endCard(dateStr, stories, { journalCount }), `${String(stories.length + 1).padStart(2, '0')}.png`);
  fs.writeFileSync(path.join(outDir, 'caption.txt'), buildCaption(dateStr, stories, spansTwoDays));
  console.log(`  ✓ caption.txt\n  → ${path.relative(ROOT, outDir)}/`);
}

main().catch((err) => { console.error(err); process.exit(1); });
